### ISSUE TITLE
ArcCreate on Linux cannot create a project from .mp3 song

### ISSUE THREAD

**Issue by astro-angelfish** [Arcthesia/ArcCreate#31]
OS Info:
```
+-$ uname -a 
Linux crystal 6.5.2-arch1-1 #1 SMP PREEMPT_DYNAMIC Wed, 06 Sep 2023 21:01:01 +0000 x86_64 GNU/Linux
```
ArcCreate version:
At commit https://github.com/Arcthesia/ArcCreate/commit/423b17883400d4e5ac0e8f7eb422c265cb797407, which is version 1.1
Desktop environment:
KDE Plasma version: 5.27.7
KDE Frameworks version: 5.109.0
Qt version: 5.15.10

I tried to create a project from a .mp3 song file, but audio file explorer seems only recognize .wav files, and I had to temporarily use ffmpeg to convert it to wav to create a beatmap.

![image](https://github.com/Arcthesia/ArcCreate/assets/22395490/6e69a51b-7075-4b36-a436-96a65d4ccefe)
![image](https://github.com/Arcthesia/ArcCreate/assets/22395490/cd7cb938-9dc7-4c76-9e77-206cb3cdfe7f)

I thought audio files also include .mp3 or similar other files.

**Comment by 0thElement** [comment]
ArcCreate does not support .mp3 files, this is intended behavior across all platforms. Ogg vorbis is supported however which will reduce file size

**Comment by astro-angelfish** [comment]
I might want to suggest to add a line to tell the people who is new to ArcCreate that a .mp3 audio should be converted before creating a beatmap for it in document files. Or an automated converted could also be OK.

And also *Audio files* in my file selection window is so ambiguous that I thought a .mp3 file is also supported or can be automatically converted.

Astro angelfish
________________________________
