### ISSUE TITLE
Feature request: change audio playback speed without changing its pitch

### ISSUE THREAD

**Issue by ofkarosia** [Arcthesia/ArcCreate#48]
Thank you for creating this amazing software. I love the practice mode. However, one thing that makes me difficult to adapt is the pitch when I change playback speed, which sounds..funny when playing. Is it possible to implement such feature(like Youtube)? I don't think it's an important feature that needs to be implemented, but it will improve our game experience.

EDIT: [Soundtouch](https://codeberg.org/soundtouch/soundtouch) might be useful.

**Comment by 0thElement** [comment]
It's unfortunately a limitation with Unity engine, any pitch bend would incur a lot of delay during playback. Your proposed solution is not real-time and would be both complicated to set up and would mean a long wait every time the playback speed is changed, which I think is too big of a drawback.
